### ISSUE TITLE
Please add support to templates! 

### ISSUE THREAD

**Issue by Paranjayy** [SimplGy/obsidian-open-file-by-magic-date#4]

**Comment by SimplGy** [comment]
What does that mean?

**Comment by Paranjayy** [comment]
> What does that mean?

Like the Plugin of Opening File with Magic Date is Awesome but only thing Lacking/Missing is Templates like Periodic Notes or Daily Notes, A Support to Magic Date Would Enhance Quality Of Life For Any User Could Be Revolutionary As in We Can Create Notes Hassle Free With Date  & Template Within 

Sorry For Low Clarity in The Title! My Bad!

**Comment by guihasparyk** [comment]
> > What does that mean?
> 
> Like the Plugin of Opening File with Magic Date is Awesome but only thing Lacking/Missing is Templates like Periodic Notes or Daily Notes, A Support to Magic Date Would Enhance Quality Of Life For Any User Could Be Revolutionary As in We Can Create Notes Hassle Free With Date & Template Within
> 
> Sorry For Low Clarity in The Title! My Bad!

Even with your explanation I still can't figure it out:
- What do you really want to achieve for yourself?
- What you are trying or tried to do till now to achieve it? 
- What is your main idea related to this plugin?
- What you are asking the developer to do specifically?

**Comment by Paranjayy** [comment]
> Even with your explanation I still can't figure it out:
>  The Plugin With Opening File With Magic Date is awesome we can create a directory like journal/DD-MM-YY.md and there could be a dropdown serving template or inserting from anything in vault for example: journal/template.md then when we open it through magic date the template which specfied would get affix it to new note which is specified before or first one as in journal/DD-MM-YY.md the affix from the template would get inserted in new note and it would be cool then we can set it in multiple folders with inbuilt package of template just same like as Daily Notes/Periodic Notes Plugin!  

> * What do you really want to achieve for yourself?
 to operate obsidian at ease with only function lacking in obsidian is we cant set default template for specified folders and stuff! it would improve quality of life with this plugin if adds support to template! 

> * What you are trying or tried to do till now to achieve it?
no i am not developer  i am just a user of magic date plugin! and i just shared my idea to make it better 

> * What is your main idea related to this plugin?
main idea specified above & and picture below like that idea 
![image](https://user-images.githubusercontent.com/120307516/232600629-f3b0a4a2-069e-4540-88f5-1b22c91217f8.png)
like this but in obsidian folders with magic date plugin! 

> * What you are asking the developer to do specifically?
asking devloper to enhance the plugin with adding support to templates

**Comment by guihasparyk** [comment]
Let me see if I understood...

What your trying to replicate on Obsidian is just like in a Notion table that everytime you create a new row/page on that table, it will automatically use a template that you defined?

If that's the case all that you need is on the Templater configuration. There you can set specific templates for notes that are created in specific folders:
1. Go to Templater settings.
2. Scroll down to Folder Templates and enable it.
3. Define the template for you chosen folder.

![Screenshot_20230418_083637_md.obsidian.jpg](https://user-images.githubusercontent.com/50344202/232705817-71394ece-739b-4115-8e83-4630ceeb0dff.jpg)

**Comment by guihasparyk** [comment]
Let me see if I understood...

What your trying to replicate on Obsidian is just like in a Notion table that everytime you create a new row/page on that table, it will automatically use a template that you defined?

If that's the case all that you need is on the Templater configuration. There you can set specific templates for notes that are created in specific folders:
1. Go to Templater settings.
2. Scroll down to Folder Templates and enable it.
3. Define the template for you chosen folder.

![Screenshot_20230418_083637_md.obsidian.jpg](https://user-images.githubusercontent.com/50344202/232705817-71394ece-739b-4115-8e83-4630ceeb0dff.jpg)

**Comment by Paranjayy** [comment]
oh damn thank you soo much 

i wasnt aware it existed my bad! sorry
